protected/models/Comentario.php
<?php

/**
 * This is the model class for table "comentario".
 *
 * The followings are the available columns in table 'comentario':
 * @property integer $id
 * @property string $contenido
 * @property string $fecha_creacion
 * @property string $autor
 * @property string $email
 * @property string $status
 * @property string $url
 * @property integer $post_id
 *
 * The followings are the available model relations:
 * @property Post $post
 */
class Comentario extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */

	const STATUS_PENDING=1;
	const STATUS_APPROVED=2;

	public function tableName()
	{
		return 'comentario';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('contenido, autor, email', 'required'),
			array('post_id', 'numerical', 'integerOnly'=>true),
			array('autor, email, url', 'length', 'max'=>128),
			array('email','email'),
			array('url','url'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, contenido, fecha_creacion, autor, email, status, url, post_id', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'post' => array(self::BELONGS_TO, 'Post', 'post_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'Id',
			'contenido' => 'Comentario',
			'fecha_creacion' => 'Fecha Creación',
			'autor' => 'Autor',
			'email' => 'Email',
			'status' => 'Status',
			'url' => 'Web',
			'post_id' => 'Post',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('contenido',$this->contenido,true);
		$criteria->compare('fecha_creacion',$this->fecha_creacion,true);
		$criteria->compare('autor',$this->autor,true);
		$criteria->compare('email',$this->email,true);
		$criteria->compare('status',$this->status,true);
		$criteria->compare('url',$this->url,true);
		$criteria->compare('post_id',$this->post_id);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Comentario the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function approve()
	{
		$this->status=Comentario::STATUS_APPROVED;
		$this->update(array('status'));
	}

	protected function beforeSave()
	{
		if(parent::beforeSave())
		{
			if($this->isNewRecord)
				$this->fecha_creacion=time();
			return true;
		}
		else
			return false;
	}

	public function getUrl($post=null)
	{
		if($post===null)
			$post=$this->post;
		return $post->url.'#c'.$this->id;
	}

	public function getAutorLink()
	{
		if(!empty($this->url))
			return CHtml::link(CHtml::encode($this->autor),$this->url);
		else
			return CHtml::encode($this->autor);
	}

	public function getPendingComentarioCount()
	{
		return $this->count('status='.self::STATUS_PENDING);
	}

	public function findRecentComentarios($limit=10)
	{
		return $this->with('post')->findAll(array(
			'condition'=>'t.status='.self::STATUS_APPROVED,
			'order'=>'t.fecha_creacion DESC',
			'limit'=>$limit,
		));
	}
}

protected/models/Post.php
<?php

/**
 * This is the model class for table "post".
 *
 * The followings are the available columns in table 'post':
 * @property integer $id
 * @property string $titulo
 * @property string $contenido
 * @property string $status
 * @property string $tags
 * @property integer $autor_id
 *
 * The followings are the available model relations:
 * @property Comentario[] $comentarios
 * @property Usuario $autor
 */
class Post extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */

	const STATUS_DRAFT=1;
	const STATUS_PUBLISHED=2;
	const STATUS_ARCHIVED=3;

	private $_oldTags;

	public function tableName()
	{
		return 'post';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('titulo, contenido, status', 'required'),
			array('autor_id', 'numerical', 'integerOnly'=>true),
			array('titulo', 'length', 'max'=>128),
			array('status','in','range'=>array(1,2,3)),
			array('tags','match','pattern'=>'/^[\w\s,]+$/','message'=>'Tags solo pueden contener caracteres alfabéticos.'),
			array('tags', 'normalizeTags'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('titulo, status', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'autor' => array(self::BELONGS_TO, 'Usuario', 'autor_id'),
			'comentarios' => array(self::HAS_MANY, 'Comentario', 'post_id','condition'=>'comentarios.status='.Comentario::STATUS_APPROVED,'order'=>'comentarios.create_time DESC'),
			'comentarioCount' => array(self::STAT, 'Comentario', 'post_id','condition'=>'status='.Comentario::STATUS_APPROVED),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'titulo' => 'Titulo',
			'contenido' => 'Contenido',
			'status' => 'Status',
			'create_time'=>'Fecha Creación',
			'update_time'=>'Fecha Actualización',
			'tags' => 'Tags',
			'autor_id' => 'Autor',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		$criteria=new CDbCriteria;

		$criteria->compare('titulo',$this->titulo,true);

		$criteria->compare('status',$this->status);

		return new CActiveDataProvider('Post', array(
			'criteria'=>$criteria,
			'sort'=>array(
				'defaultOrder'=>'status, update_time DESC',
			),
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Post the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	public function getUrl(){
		return Yii::app()->createUrl('post/view', array(
			'id'=>$this->id,
			'titulo'=>$this->titulo,
		));
	}

	public function getTagLinks()
	{
		$links=array();
		foreach(Tag::string2array($this->tags) as $tag)
			$links[]=CHtml::link(CHtml::encode($tag), array('post/index', 'tag'=>$tag));
		return $links;
	}

	public function normalizeTags($attributes,$params){
		$this->tags = Tag::array2string(array_unique(Tag::string2array($this->tags)));
	}

	protected function beforeSave(){
		if(parent::beforeSave()){
			if($this->isNewRecord){
				$this->create_time=$this->update_time=time();
				$this->autor_id=Yii::app()->user->id;
			}
			else
				$this->update_time=time();
			return true;
		}
		else
			return false;
	}


	protected function afterSave(){
		parent::afterSave();
		Tag::model()->updateFrecuencia($this->_oldTags, $this->tags);
	}

	protected function afterFind(){
		parent::afterFind();
		$this->_oldTags=$this->tags;
	}

	protected function afterDelete(){
		parent::afterDelete();
		Comentario::model()->deleteAll('post_id='.$this->id);
		Tag::model()->updateFrecuencia($this->tags, '');
	}

	public function addComentario($comentario)
	{
		if(Yii::app()->params['commentNeedApproval'])
			$comentario->status=Comentario::STATUS_PENDING;
		else
			$comentario->status=Comentario::STATUS_APPROVED;
		$comentario->post_id=$this->id;
		return $comentario->save();
	}
}

protected/controllers/PostController.php
<?php

class PostController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform any actions
				'actions'=>array('fileUpload','imageUpload', 'imageList', 'admin', 'create', 'update'),
				'users'=>array('@'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView(){

		$post=$this->loadModel();
		$comentario=$this->newComentario($post);

		$this->render('view',array(
			'model'=>$post,
			'comentario'=>$comentario,
		));
	}

	public function actionSuggestTags()
	{
		if(isset($_GET['q']) && ($keyword=trim($_GET['q']))!=='')
		{
			$tags=Tag::model()->suggestTags($keyword);
			if($tags!==array())
				echo implode("\n",$tags);
		}
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Post;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate()
	{
		$model=$this->loadModel();

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Post']))
		{
			$model->attributes=$_POST['Post'];
			if($model->save())
				$this->redirect(array('view','id'=>$model->id));
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete()
	{
		if(Yii::app()->request->isPostRequest){

			//we only allow deletion via POST request
			$this->loadModel()->delete();

			// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			if(!isset($_POST['ajax']))
				$this->redirect(array('index'));
		}
		else
			throw new CHttpException(400, 'Petición invalida. Por favor no repita esta petición de nuevo');
			
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		/*$dataProvider=new CActiveDataProvider('Post');
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));*/
		$criteria=new CDbCriteria(array(
			'condition'=>'status='.Post::STATUS_PUBLISHED,
			'order'=>'update_time DESC',
			'with'=>'comentarioCount',
		));
		if(isset($_GET['tag']))
			$criteria->addSearchCondition('tags',$_GET['tag']);
		
		$dataProvider=new CActiveDataProvider('Post', array(
			'pagination'=>array(
				'pageSize'=>Yii::app()->params['postsPerPage'],
			),
			'criteria'=>$criteria,
		));

		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Post('search');
		if(isset($_GET['Post']))
			$model->attributes=$_GET['Post'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Post the loaded model
	 * @throws CHttpException
	 */
	/*public function loadModel($id)
	{
		$model=Post::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}*/
	private $_model;

	public function loadModel(){
		if($this->_model===null){
			if(isset($_GET['id'])){
				if(Yii::app()->user->isGuest)
					$condition='status='.Post::STATUS_PUBLISHED.' OR status='.Post::STATUS_ARCHIVED;
				else
					$condition='';
				$this->_model=Post::model()->findByPk($_GET['id'], $condition);
			}
			if($this->_model===null)
				throw new CHttpException(404,'La página solicitada no existe');
		}
		return $this->_model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Post $model the model to be validated
	 */

	protected function newComentario($post)
	{
		$comentario=new Comentario;
		if(isset($_POST['ajax']) && $_POST['ajax']==='comment-form')
		{
			echo CActiveForm::validate($comentario);
			Yii::app()->end();
		}
		if(isset($_POST['Comentario']))
		{
			$comentario->attributes=$_POST['Comentario'];
			if($post->addComentario($comentario))
			{
				if($comentario->status==Comentario::STATUS_PENDING)
					Yii::app()->user->setFlash('commentSubmitted','Gracias por su comentario. Su comentario será publicado tras su aprobación.');
				$this->refresh();
			}
		}
		return $comentario;
	}

	public function actions()
    {
        return array(
            'fileUpload'=>array(
                'class'=>'ext.redactor.actions.FileUpload',
                'uploadCreate'=>true,
            ),
            'imageUpload'=>array(
                'class'=>'ext.redactor.actions.ImageUpload',
                'uploadCreate'=>true,
            ),
            'imageList'=>array(
                'class'=>'ext.redactor.actions.ImageList',
            ),
        );
    }
}

protected/views/post/_comments.php
<?php foreach($comments as $comentario): ?>
<div class="comment" id="c<?php echo $comentario->id; ?>">

	<?php echo CHtml::link("#{$comentario->id}", $comentario->getUrl($post), array(
		'class'=>'cid',
		'title'=>'Permalink to this comment',
	)); ?>

	<div class="author">
		<?php echo $comentario->autorLink; ?> says:
	</div>

	<div class="time">
		<?php echo date('F j, Y \a\t h:i a',$comentario->fecha_creacion); ?>
	</div>

	<div class="content">
		<?php echo nl2br(CHtml::encode($comentario->contenido)); ?>
	</div>

</div><!-- comment -->
<?php endforeach; ?>

protected/views/post/_form.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>
<div class="form">

<?php $form=$this->beginWidget('CActiveForm'); ?>

	<p class="note">Fields with <span class="required">*</span> are required.</p>

	<?php echo $form->errorSummary($model); ?>

	<div class="row">
		<?php echo $form->labelEx($model,'titulo'); ?>
		<?php echo $form->textField($model,'titulo',array('size'=>80,'maxlength'=>128)); ?>
		<?php echo $form->error($model,'titulo'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'contenido'); ?>
		<?php $this->widget('ext.redactor.ERedactorWidget', 
				array(
			        'model' => $model,
			        'attribute' => 'contenido',
			       	'htmlOptions'=>array(
		                'rows'=>20
		            ),
		            'options'=>array(
		                'cleanOnPaste'=>false,
		                'linebreaks'=>false,
		                'replaceDivs'=>false,
		                'allowedTags'=>array('span', 'button', 'i', 'div', 'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'ul', 'li', 'ol', 'a', 'img', 'br', 'span'),
		                'fileUpload'=>Yii::app()->createUrl('post/fileUpload',array(
		                    'attr'=>'contenido',
		                )),
		                'fileUploadErrorCallback'=>new CJavaScriptExpression(
		                    'function(obj,json) { alert(json.error); }'
		                ),
		                'imageUpload'=>Yii::app()->createUrl('post/imageUpload',array(
		                    'attr'=>'contenido',
		                )),
		                'imageGetJson'=>Yii::app()->createUrl('post/imageList',array(
		                    'attr'=>'contenido',
		                )),
		                'imageUploadErrorCallback'=>new CJavaScriptExpression(
		                    'function(obj,json) { alert(json.error); }'
		                ),
		            ),
			    )
		    );
    	?>
		<?php echo $form->error($model,'contenido'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'status'); ?>
		<?php echo $form->dropDownList($model,'status',Lookup::items('PostStatus')); ?>
		<?php echo $form->error($model,'status'); ?>
	</div>

	<div class="row">
		<?php echo $form->labelEx($model,'tags'); ?>
		<?php $this->widget('CAutoComplete', array(
			'model'=>$model,
			'attribute'=>'tags',
			'url'=>array('suggestTags'),
			'multiple'=>true,
			'htmlOptions'=>array('size'=>50),
		)); ?>
		<p class="hint">Please separate different tags with commas.</p>
		<?php echo $form->error($model,'tags'); ?>
	</div>

	<div class="row buttons">
		<?php echo CHtml::submitButton($model->isNewRecord ? 'Create' : 'Save'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/post/_view.php
<div class="post">
	<div class="title">
		<?php echo CHtml::link(CHtml::encode($data->titulo), $data->url); ?>
	</div>
	<div class="author">
		posted by <?php echo $data->autor->nombre . ' on ' . date('F j, Y',$data->create_time); ?>
	</div>
	<div class="content">
		<?php
			$this->beginWidget('CMarkdown', array('purifyOutput'=>true));
			echo $data->contenido;
			$this->endWidget();
		?>
	</div>
	<div class="nav">
		<b>Tags:</b>
		<?php echo implode(', ', $data->tagLinks); ?>
		<br/>
		<?php echo CHtml::link('Permalink', $data->url); ?> |
		<?php echo CHtml::link("Comentarios ({$data->comentarioCount})",$data->url.'#comentarios'); ?> |
		Última actualización <?php echo date('F j, Y',$data->update_time); ?>
	</div>
</div>

protected/views/post/admin.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'Manage',
);

?>

<h1>Manage Posts</h1>


<?php $this->widget('zii.widgets.grid.CGridView', array(
	'dataProvider'=>$model->search(),
	'filter'=>$model,
	'columns'=>array(
		array(
			'name'=>'titulo',
			'type'=>'raw',
			'value'=>'CHtml::link(CHtml::encode($data->titulo), $data->url)'
		),
		array(
			'name'=>'status',
			'value'=>'Lookup::item("PostStatus",$data->status)',
			'filter'=>Lookup::items('PostStatus'),
		),
		array(
			'name'=>'create_time',
			'type'=>'datetime',
			'filter'=>false,
		),
		array(
			'class'=>'CButtonColumn',
		),
	),
)); ?>

protected/views/post/create.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts'=>array('index'),
	'Create Post',
);

$this->menu=array(
	array('label'=>'List Post', 'url'=>array('index')),
	array('label'=>'Manage Post', 'url'=>array('admin')),
);
?>

<h1>Create Post</h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/post/index.php
<?php
/* @var $this PostController */
/* @var $dataProvider CActiveDataProvider */

$this->breadcrumbs=array(
	'Posts',
);

$this->menu=array(
	array('label'=>'Create Post', 'url'=>array('create')),
	array('label'=>'Manage Post', 'url'=>array('admin')),
);
?>

<h1>Posts</h1>

<?php if(!empty($_GET['tag'])): ?>
<h1>Posts Tagged with <i><?php echo CHtml::encode($_GET['tag']); ?></i></h1>
<?php endif; ?>

<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
	'template'=>"{items}\n{pager}",
)); ?>

protected/views/post/update.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts'=>array('index'),
	$model->id=>array('view','id'=>$model->id),
	'Update',
);

$this->menu=array(
	array('label'=>'List Post', 'url'=>array('index')),
	array('label'=>'Create Post', 'url'=>array('create')),
	array('label'=>'View Post', 'url'=>array('view', 'id'=>$model->id)),
	array('label'=>'Manage Post', 'url'=>array('admin')),
);
?>

<h1>Update Post <?php echo $model->id; ?></h1>

<?php $this->renderPartial('_form', array('model'=>$model)); ?>

protected/views/post/view.php
<?php
$this->breadcrumbs=array(
	$model->titulo,
);
$this->pageTitle=$model->titulo;
?>

<?php $this->renderPartial('_view', array(
	'data'=>$model,
)); ?>

<div id="comments">
	<?php if($model->comentarioCount>=1): ?>
		<h3>
			<?php echo $model->comentarioCount>1 ? $model->comentarioCount . ' comentarios' : '1 comentario'; ?>
		</h3>

		<?php $this->renderPartial('_comments',array(
			'post'=>$model,
			'comments'=>$model->comments,
		)); ?>
	<?php endif; ?>

	<h3>Deja tu comentario</h3>

	<?php if(Yii::app()->user->hasFlash('commentSubmitted')): ?>
		<div class="flash-success">
			<?php echo Yii::app()->user->getFlash('commentSubmitted'); ?>
		</div>
	<?php else: ?>
		<?php $this->renderPartial('/comentario/_form',array(
			'model'=>$comentario,
		)); ?>
	<?php endif; ?>

</div><!-- comments -->